In [ ]:
# This is the float.64 square wrapper 2022-10-07 - done, wrote flt64 file set
    # to model
# For structuring the gene expression data for feed to MNIST 2D conv VAE

# From nb_A_data_structure____00.ipynb (in image gen original)
# Convert from Casey Greene format data back to original full gene expression features

# Overfilling the MAD 8 by 5k data with too many zeroes
    # Only have 5k featus, 144 by 144 is too much
    # Rebuild from a_data_structure_00-Copy1.ipynb

In [ ]:
# Library organization strategy
A_data_structure
B_model_build_train
C_synth_latent_gen
D_UMAP_fnctn_plot
E_ML_classification

# other notes:
    # latent space dimension goal 50 to 500
    # UMAP figures at various points of data transformation

In [1]:
# target dir for square files
pwd

'/Users/karlberb/Desktop/RNB00978/sample_count/sample_gen/image_gen/a_data_structure'

In [ ]:
# b_model_ops_00 will read from a_data_structure
# that will send to c_latent_synth__00 (want two methods here - pairwise averaging and rejection method)
# then UMAP_figs_00

In [ ]:
# Start point

In [1]:
date = '2022-10-07' # Friday, make umap story board
version = 'a_data_structure_00.ipynb' # In the controlled repo now

In [2]:
import glob as glob
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

In [3]:
pwd

'/Users/karlberb/Desktop/RNB00978/sample_count/sample_gen/synthetic_TCGA_data_gen/a_data_structure'

In [ ]:
# Casey Greene chorort compile and feature pruning:
# reduce to 5k: med_abs_dev.ipynb

In [4]:
ls

a_data_structure_00-Copy1.ipynb  intersect_template.ipynb
a_data_structure_00.ipynb        mir_files/
intersect_00.ipynb               mir_intrsct/


In [5]:
# Read 26 cancer gene-expression files
gxp_file_paths = sorted(glob.glob('/Users/karlberb/work/sample_count/smpl_gen/gexp_files/*.tsv'))

In [ ]:
# check pre-train / fine-tune across differing input file feauture counts
# add the log conversion prior to normalization
# zero-fill is blurring transfer learning performance evaluation, fix with 1Dconv version

In [ ]:
# target output dir
sample_gen/synthetic_TCGA_data_gen/a_data_structure/blca_brca_square_full

In [6]:
# Read bladder, full file, no intersect, check later, go to float.64 conversion now
file  = pd.read_csv(gxp_file_paths[1],
                       sep = '\t',
                       index_col = 0)

In [42]:
# BRCA read
file  = pd.read_csv(gxp_file_paths[2],
                       sep = '\t',
                       index_col = 0)

In [43]:
# Wrap BLCA for pretrain, then BRCA

train, test = train_test_split(file) # no seed, will get a different trn/tst splt each time

trn_empty = [] # append model-formatted numpy arrays of gene expression values
trn_y_list = []

for j, sample in enumerate(train.index): # okay, start going through the train object
    gene_row = list(train.iloc[j,1:]) # extract sample gene expression

    base = np.array(gene_row + (
        20736 - len(
            # gene_row)) * [0],dtype=np.uint8).reshape(144,144,1)
                        gene_row)) * [0]).reshape(144,144,1)

    trn_empty.append(base)
    y = train.iloc[j,0]
    trn_y_list.append(y)

formatted = np.array(trn_empty)
formatted = formatted/255 # This normalization for unint 8, pull in the MinMaxScaler
        # for data structure version one
        # Start version one of this d_struct from here
        # Send better f64 files to model b_mod_v1, time for outlier clipping, log x-form, etc

      # END version 0 <------------- r0 png loss curve for BLCA in model dir
    
    # coordinate corrected versions in v2 of data structure and model

X_train_new = formatted

print('train loop done')

# Start processing the test data, same as above
tst_empty = []
tst_y_list = []

for j, sample in enumerate(test.index):
    gene_row = list(test.iloc[j,1:])
    base = np.array(gene_row + (
        20736 - len(
            # gene_row)) * [0],
                        gene_row)) * [0]
                    # dtype=np.uint8 # <---
                   ).reshape(144,144,1)
    tst_empty.append(base)
    y = test.iloc[j,0]
    tst_y_list.append(y)
formatted = np.array(tst_empty)
formatted = formatted/255 # test normalization
X_test_new = formatted

print('done')

train loop done
done


In [45]:
trn_y_out # Lost index labels, might need for plot eventually

Labels
0    BRCA_2
1    BRCA_1
2    BRCA_2
3    BRCA_2
4    BRCA_4
..      ...
741  BRCA_2
742  BRCA_1
743  BRCA_1
744  BRCA_3
745  BRCA_1

[746 rows x 1 columns]

In [ ]:
# Write the y's, not used for the UMAP, just keeping ready for sample gen ops

In [44]:
trn_y_out = pd.DataFrame(trn_y_list,columns = ['Labels'])
trn_y_out.to_csv('brca_full_flt64_y_trn.tsv',
                sep = '\t',
                )
tst_y_out = pd.DataFrame(tst_y_list,columns = ['Labels'])
tst_y_out.to_csv('brca_full_flt64_y_tst.tsv',
                sep = '\t',
                )

In [ ]:
# Bladder

In [8]:
len(trn_y_list) # bladder check

299

In [9]:
trn_y_out = pd.DataFrame(trn_y_list, columns = ['Labels'])

In [16]:
trn_y_out.to_csv('blca_full_flt64_y_trn.tsv',
                sep = '\t',
                )

In [17]:
tst_y_out = pd.DataFrame(tst_y_list,columns = ['Labels'])
tst_y_out.to_csv('blca_full_flt64_y_tst.tsv',
                sep = '\t',
                )

In [14]:
len(tst_y_out) # BLCA check

100

In [ ]:
# end y zone

In [ ]:
# write brca, no checks, second run, for fine tune, blca devel and inspect below

### X files

In [46]:
np.save('brca_full_flt64_X_trn', X_train_new)

In [47]:
np.save('brca_full_flt64_X_tst.npy', X_test_new)

In [ ]:
# End, go to model 2022-10-07 Friday morning

#### blca flt 64 devel, inspect, and write-out (run first):

In [ ]:
# Start X checks

In [18]:
X_train_new.shape # main variable trn

(299, 144, 144, 1)

In [19]:
X_test_new.shape # main variable tst

(100, 144, 144, 1)

In [20]:
type(X_train_new)

numpy.ndarray

In [21]:
len(X_train_new) # dim pos 0

299

In [25]:
X_train_new[0].shape # shape of the first sample

(144, 144, 1)

In [28]:
X_train_new[0][0].shape # first row

(144, 1)

In [29]:
X_train_new[0][0] # second element of the shape of this object is one
# one list of 144 lists? why is every value a list? because it could be three RBG channels?

array([[0.00000000e+00],
       [3.94470588e-02],
       [3.63772549e-02],
       [4.39647059e-01],
       [3.22552941e+00],
       [0.00000000e+00],
       [3.79905882e+00],
       [5.83294118e-03],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [1.94427451e-02],
       [3.49964706e-02],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [5.83294118e-03],
       [1.15490196e+00],
       [1.14709804e-01],
       [0.00000000e+00],
       [2.33270588e+01],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [1.94431373e-03],
       [5.71607843e+00],
       [0.00000000e+00],
       [7.67803922e-02],
       [0.00000000e+00],
       [0.00000000e+00],
       [4.89882353e-01],
       [4.97921569e+00],
       [3.91960784e+01],
       [2.64611765e+00],
       [7.77686275e-03],
       [0.00000000e+00],
       [4.37843137e+00],
       [0.00000000e+00],


In [34]:
X_train_new[0][0][0] # first sample, first pixel row, first element

array([0.])

In [33]:
X_train_new[0][0][37]

array([0.])

In [35]:
X_train_new[0][0][38] # find an actual gene expression value

array([4.37843137])

In [36]:
X_train_new[0][0][38][0] # pull the singe gene expression value from the RGB list

4.37843137254902

In [37]:
type(X_train_new[0][0][38][0]) # Correct, send to model set up to take this dtype

numpy.float64

In [38]:
np.save('blca_full_flt64_X_trn', X_train_new)

In [39]:
len(X_test_new)

100

In [40]:
np.save('blca_full_flt64_X_tst', X_test_new)

In [ ]:
# done, with flt 64 wrap for blca and brca

In [ ]:
# Original uint8 file write, probly back in og img gen dir

In [ ]:
BLCA_square.to_csv('nb_A_data_out/'+version+
                   date+'_'+
                   file.index.name+'_'+
                   'square.tsv',
                    sep = '\t',
                   )