In [ ]:
# V3 - Run raw vs. decoded samples into a UMAP
# Validation of quality of embedding

In [ ]:
# Operational notes
# Turn up latent space dimension with grid: 50 to 500
# need in a unified dataframe to accomplish this 
# running reshape, flatten
# label train and test
# UMAP automation, in process

In [4]:
pwd

'/Users/karlberb/Desktop/RNB00978/sample_count/sample_gen/synthetic_TCGA_data_gen/a_data_structure'

In [ ]:
# target dirs for three sets of square files

In [5]:
ls # looks pretty good, why is model outputting flt.32s though?

a_data_structure_00-Copy1.ipynb  blca_brca_flt64_sqrs/
a_data_structure_00.ipynb        intersect_00.ipynb
a_data_structure_01.ipynb        intersect_template.ipynb
a_data_structure_02.ipynb        mir_files/
a_data_structure_03.ipynb        mir_intrsct/


In [ ]:
# c module note
# two methods here - pairwise averaging and rejection method

In [6]:
%whos

Variable           Type        Data/Info
----------------------------------------
MinMaxScaler       type        <class 'sklearn.preproces<...>sing._data.MinMaxScaler'>
date               str         2022-10-10
glob               module      <module 'glob' from '/Use<...>3/lib/python3.9/glob.py'>
np                 module      <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
pd                 module      <module 'pandas' from '/U<...>ages/pandas/__init__.py'>
train_test_split   function    <function train_test_split at 0x7f8945a439d0>
version            str         a_data_structure_03.ipynb


In [2]:
date = '2022-10-10' # Friday, make umap story board
version = 'a_data_structure_03.ipynb' # In the version controlled repo now

In [3]:
import glob as glob
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [13]:
# get template code for the MinMax inverse, 
# to b-module model decoder or d-module UMAP input

In [7]:
# Read 26 cancer gene-expression files
gxp_file_paths = sorted(glob.glob('/Users/karlberb/work/sample_count/smpl_gen/gexp_files/*.tsv'))

In [ ]:
# check pre-train / fine-tune across differing input file feauture counts
# add the log conversion prior to normalization
# zero-fill is blurring transfer learning performance evaluation, fix with 1Dconv version

#### Target output dirs
sample_gen/synthetic_TCGA_data_gen/a_data_structure/blca_brca_square_full/MinMax
./a_data_structure/blca_brca_square_full/clip_outlrs
./a_data_structure/blca_brca_square_full/log_xfrm

In [ ]:
# dirs built, run the latent space grid on all three

In [ ]:
# idea - only apply log transform to upper segment of vals (?)
# div256 is artifact from original image version conversion
# compare pre-post layer error fix from original example ?

In [14]:
# Read bladder, full file, no intersect
file  = pd.read_csv(gxp_file_paths[1],
                       sep = '\t',
                       index_col = 0)

In [15]:
file.index.name

'BLCA'

In [ ]:
# add * 1D conv model * then transformer to the grid

In [ ]:
# want two models, two cancers, two data types, data structures, ...
# get a decent grid going with the auto UMAP

In [27]:
# BRCA read
file  = pd.read_csv(gxp_file_paths[2],
                       sep = '\t',
                       index_col = 0)

In [28]:
file.index.name

'BRCA'

In [16]:
type(file)

pandas.core.frame.DataFrame

In [17]:
file = MinMaxScaler().fit_transform(
    file.iloc[:,1:])

In [18]:
type(file) # converts to array from DF
    # possible d-type failure point

numpy.ndarray

In [21]:
type(file[0][0]) # nope, still og dtype

numpy.float64

In [31]:
file.shape

(399, 20531)

In [ ]:
# File is uniformly rescaled

In [22]:
train, test = train_test_split(file)

In [23]:
train.shape # X

(299, 20531)

In [33]:
train[0].shape # why is this a tuple with an empty second value?
                # kinda want to put a '1' in for channel in 1D conv model

(20531,)

In [ ]:
# square wrap function devel
    # order swap of MinMax scale with Trn/Tst split breaks
    # row iteration

In [24]:
splt = train.copy()

In [25]:
X_list = []
y_list = []

In [27]:
for j, sample in enumerate(splt):
    break

In [30]:
sample.shape

(20531,)

In [28]:
j

0

In [35]:
gene_row = list(sample)

In [37]:
len(gene_row)

20531

In [38]:
filler = gene_row + (20736 - len(gene_row)) * [0]

In [39]:
len(filler)

20736

In [40]:
flr_ary = np.array(filler)

In [42]:
flr_ary.shape

(20736,)

In [44]:
flr_ary_sqr = flr_ary.reshape(144,144,1)

In [ ]:
def wrap(splt):
    X_list = []
    y_list = []
    for j, sample in enumerate(splt.index):
        gene_row = list(sample)
        filler = gene_row + (20736 - len(gene_row)) * [0]
        flr_ary = np.array(filler)
        flr_ary_sqr = flr_ary.reshape(144,144,1)
        X_list.append(flr_ary_sqr)
    return(X)

In [ ]:
# v2 version

In [29]:
# Wrap BLCA for pretrain, then BRCA
# Main question here is whether to run MinMax
# on train and test independently
    # mirror the invert function regardless

print('starting '+file.index.name)

train, test = train_test_split(file) # normed above, v3 test

# train.iloc[:,1:] = MinMaxScaler().fit_transform(
#     train.iloc[:,1:]) # or just run on the file - done

# test.iloc[:,1:] = MinMaxScaler().fit_transform(test.iloc[:,1:])

trn_empty = [] # append model-formatted numpy arrays of gexp values
trn_y_list = []

for j, sample in enumerate(train.index): # go through the train object
    gene_row = list(train.iloc[j,1:]) # extract sample gene expression

    base = np.array(gene_row + (
        20736 - len(
            # gene_row)) * [0],dtype=np.uint8).reshape(144,144,1)
                        gene_row)) * [0]).reshape(144,144,1)

    trn_empty.append(base)
    y = train.iloc[j,0]
    trn_y_list.append(y)
X_train_new  = np.array(trn_empty)
# formatted = np.array(trn_empty)
# formatted = formatted/255 # This normalization for unint 8, pull in the MinMaxScaler
        # for data structure version one
        # Start version one of this d_struct from here
        # Send better f64 files to model b_mod_v1, time for outlier clipping, log x-form, etc

      # END version 0 <------------- r0 png loss curve for BLCA in model dir
    
    # coordinate corrected versions in v2 of data structure and model
    
# formatted = MinMaxScaler(formatted) # Completly wrong

# X_train_new = MinMaxScaler().fit_transform(formatted) # last fail

# X_train_new = formatted

print('MinMax train loop done')

# Start processing the test data, same as above [toggling for MinMax test]

tst_empty = []
tst_y_list = []

test.iloc[:,1:] = MinMaxScaler().fit_transform(test.iloc[:,1:])

for j, sample in enumerate(test.index):
    gene_row = list(test.iloc[j,1:])
    base = np.array(gene_row + (
        20736 - len(
            # gene_row)) * [0],
                        gene_row)) * [0]
                    # dtype=np.uint8 # <---
                   ).reshape(144,144,1)
    tst_empty.append(base)
    y = test.iloc[j,0]
    tst_y_list.append(y)
X_test_new = np.array(tst_empty)
# formatted = formatted/255 # test normalization
# X_test_new = formatted

print('done')

starting BRCA
MinMax train loop done
done


In [24]:
file.index.name # Still losing index, dont care right now

'BLCA'

In [30]:
file.index.name # Check, run 2

'BRCA'

In [31]:
np.save(
    'blca_brca_flt64_sqrs/MinMax/'+file.index.name+'_MinMax_X_trn',
    X_train_new)

np.save(
    'blca_brca_flt64_sqrs/MinMax/'+file.index.name+'_MinMax_X_tst.npy', # robust against ext incl
        X_test_new)

In [32]:
trn_y_out = pd.DataFrame(trn_y_list,columns = ['Labels'])
trn_y_out.to_csv('blca_brca_flt64_sqrs/MinMax/'+file.index.name+'_MinMax_y_trn.tsv',
                sep = '\t',
                )
tst_y_out = pd.DataFrame(tst_y_list,columns = ['Labels'])
tst_y_out.to_csv('blca_brca_flt64_sqrs/MinMax/'+file.index.name+'_MinMax_y_tst.tsv',
                sep = '\t',
                )

In [21]:
X_train_new # looks pretty good

array([[[[0.00000000e+00],
         [1.00325930e-01],
         [2.41180480e-01],
         ...,
         [8.49700757e-02],
         [6.30716818e-02],
         [1.10217470e-01]],

        [[1.14851667e-01],
         [1.74943592e-01],
         [3.91339207e-01],
         ...,
         [7.11519344e-02],
         [1.39899475e-02],
         [0.00000000e+00]],

        [[0.00000000e+00],
         [1.84413064e-03],
         [0.00000000e+00],
         ...,
         [7.96775513e-02],
         [1.97273754e-01],
         [1.75369708e-01]],

        ...,

        [[2.44156677e-01],
         [6.40961394e-01],
         [2.07762700e-01],
         ...,
         [3.51270520e-03],
         [6.56183074e-02],
         [2.60783757e-02]],

        [[1.64730188e-01],
         [5.34494721e-01],
         [2.34988529e-01],
         ...,
         [0.00000000e+00],
         [0.00000000e+00],
         [0.00000000e+00]],

        [[0.00000000e+00],
         [0.00000000e+00],
         [0.00000000e+00],
         ...,
 

In [ ]:
# remember to fix the layers on the model per error in original example

In [ ]:
# End the MinMax file write

In [ ]:
# Original div256_float64 fail from version 00

In [45]:
trn_y_out # Lost index labels, might need for plot eventually

Labels
0    BRCA_2
1    BRCA_1
2    BRCA_2
3    BRCA_2
4    BRCA_4
..      ...
741  BRCA_2
742  BRCA_1
743  BRCA_1
744  BRCA_3
745  BRCA_1

[746 rows x 1 columns]

In [ ]:
# Write the y's, not used for the UMAP, just keeping ready for sample gen ops

In [44]:
trn_y_out = pd.DataFrame(trn_y_list,columns = ['Labels'])
trn_y_out.to_csv('brca_full_flt64_y_trn.tsv',
                sep = '\t',
                )
tst_y_out = pd.DataFrame(tst_y_list,columns = ['Labels'])
tst_y_out.to_csv('brca_full_flt64_y_tst.tsv',
                sep = '\t',
                )

In [ ]:
# Bladder

In [8]:
len(trn_y_list) # bladder check

299

In [9]:
trn_y_out = pd.DataFrame(trn_y_list, columns = ['Labels'])

In [16]:
trn_y_out.to_csv('blca_full_flt64_y_trn.tsv',
                sep = '\t',
                )

In [17]:
tst_y_out = pd.DataFrame(tst_y_list,columns = ['Labels'])
tst_y_out.to_csv('blca_full_flt64_y_tst.tsv',
                sep = '\t',
                )

In [14]:
len(tst_y_out) # BLCA check

100

In [ ]:
# end y zone

In [ ]:
# write brca, no checks, second run, for fine tune, blca devel and inspect below

### X files

In [46]:
np.save('brca_full_flt64_X_trn', X_train_new)

In [47]:
np.save('brca_full_flt64_X_tst.npy', X_test_new)

In [ ]:
# End, go to model 2022-10-07 Friday morning

#### blca flt 64 devel, inspect, and write-out (run first):

In [ ]:
# Start X checks

In [18]:
X_train_new.shape # main variable trn

(299, 144, 144, 1)

In [19]:
X_test_new.shape # main variable tst

(100, 144, 144, 1)

In [20]:
type(X_train_new)

numpy.ndarray

In [21]:
len(X_train_new) # dim pos 0

299

In [25]:
X_train_new[0].shape # shape of the first sample

(144, 144, 1)

In [28]:
X_train_new[0][0].shape # first row

(144, 1)

In [29]:
X_train_new[0][0] # second element of the shape of this object is one
# one list of 144 lists? why is every value a list? because it could be three RBG channels?

array([[0.00000000e+00],
       [3.94470588e-02],
       [3.63772549e-02],
       [4.39647059e-01],
       [3.22552941e+00],
       [0.00000000e+00],
       [3.79905882e+00],
       [5.83294118e-03],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [1.94427451e-02],
       [3.49964706e-02],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [5.83294118e-03],
       [1.15490196e+00],
       [1.14709804e-01],
       [0.00000000e+00],
       [2.33270588e+01],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [1.94431373e-03],
       [5.71607843e+00],
       [0.00000000e+00],
       [7.67803922e-02],
       [0.00000000e+00],
       [0.00000000e+00],
       [4.89882353e-01],
       [4.97921569e+00],
       [3.91960784e+01],
       [2.64611765e+00],
       [7.77686275e-03],
       [0.00000000e+00],
       [4.37843137e+00],
       [0.00000000e+00],


In [34]:
X_train_new[0][0][0] # first sample, first pixel row, first element

array([0.])

In [33]:
X_train_new[0][0][37]

array([0.])

In [35]:
X_train_new[0][0][38] # find an actual gene expression value

array([4.37843137])

In [36]:
X_train_new[0][0][38][0] # pull the singe gene expression value from the RGB list

4.37843137254902

In [37]:
type(X_train_new[0][0][38][0]) # Correct, send to model set up to take this dtype

numpy.float64

In [38]:
np.save('blca_full_flt64_X_trn', X_train_new)

In [39]:
len(X_test_new)

100

In [40]:
np.save('blca_full_flt64_X_tst', X_test_new)

In [ ]:
# done, with flt 64 wrap for blca and brca

In [ ]:
# Original uint8 file write, probly back in og img gen dir

In [ ]:
BLCA_square.to_csv('nb_A_data_out/'+version+
                   date+'_'+
                   file.index.name+'_'+
                   'square.tsv',
                    sep = '\t',
                   )